#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/scrooloose/nerdcommenter.git",
  "git://github.com/wincent/Command-T",
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/tsaleh/vim-align.git",
  "git://github.com/tsaleh/vim-supertab.git",
  "git://github.com/tsaleh/vim-tcomment.git",
  #"git://github.com/kevinw/pyflakes-vim.git", # call git://github.com/kevinw/pyflakes in containing directory
  "git://repo.or.cz/vcscommand",
  "git://github.com/tpope/vim-unimpaired.git",
  "git://github.com/vim-bundles/fuzzyfinder.git",
  "git://github.com/vim-scripts/SearchComplete.git",
]

vim_org_scripts = [
  #["IndexedSearch", "7062",  "plugin"],
  ["gist",          "12732", "plugin"],
  ["taglist",       "7701",  "zip"],
  ["wombat256",     "2465", "colors"],
  ["wombat",        "6657", "colors"],
  ["camelcase",     "8708", "autoload"],
  ["cpp",     "13033", "indent"], # http://www.vim.org/scripts/script.php?script_id=2636
  ["cpp", "6320", "syntax"],  # http://www.vim.org/scripts/script.php?script_id=1640
  ["python", "12804", "syntax"], # http://www.vim.org/scripts/script.php?script_id=790
  ["python", "4316", "indent"], # http://www.vim.org/scripts/script.php?script_id=974
  ["pydiction", "11062", "zip"], #http://www.vim.org/scripts/script.php?script_id=850
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

trash = ARGV.include?('--trash')

if trash
   puts "Trashing everything (lookout!)" 
   Dir["*"].each {|d| FileUtils.rm_rf d }
end 

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  if !trash && File.exists?(dir)
    puts " Skipping #{dir}"
    next
  end
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.#{script_type == 'zip' ? 'zip' : 'vim'}")
  if !trash && File.exists?(local_file)
    puts " Skipping #{local_file}"
    next
  end
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
  if script_type == 'zip'
    %x(unzip -d #{name} #{local_file})
  end
end

